### ISSUE TITLE
Output reserved key

### ISSUE THREAD

**Issue by erhenjt** [rany2/warp.sh#10]
There are scripts out there that have implemented this feature, such as https://github.com/chise0713/warp-reg.sh
But it it doesn't support teams/zero trust.

**Comment by rany2** [comment]
This script does that too, it's the "client id."

**Comment by rany2** [comment]
Why would you need the reserved key/client id in hex/dec? Is str enough like this script currently does? What are you using it for?

**Comment by rany2** [comment]
Thanks, I'll add it. What's the benefit of this reserved key/client id anyway? Warp works fine with a standard Wireguard client without a reserved key

**Comment by rany2** [comment]
> But it seems that it's only mandatory on some of the servers?

Interesting, I've never had to use it but I did notice that I needed to disconnect/connect WG connections for the first time I connected to WARP for a couple of times before it worked? So maybe that's why? After I did that it worked without any hiccups. 

I will convert these to dec/hex of course, I'm a bit confused why the program you linked to doesn't just accept it in base64.
